[package]
name = "audio_recorder_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alsa = "0.8"
chrono = "0.4"
crossbeam = "0.8"
libc = "0.2"
rppal = "0.17"